# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - 5432:5432
  calendso:
    build: .
    restart: always
    ports:
      - 3000:3000
      - 5555:5555
    env_file: .env
    depends_on:
      - db

  calendso-nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - timbre-java
      - timbre-frontend
    command:
      '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done &
      nginx -g "daemon off;"'''

  calendso-certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint:
      "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait
      $${!}; done;'"

volumes:
  database-data: